# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Colin's Musings and Ramblings
tagline:          A repository for Colin's thoughts on the web
url:              http://cdurant.github.io
paginate:         1
baseurl:          /
author:
  name:           Colin DuRant
  url:            https://twitter.com/colin_durant
  email:          colin.durant@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:          https://github.com/cdurant/cdurant.github.io
